### ISSUE TITLE
UNOBB: OBB files are actually not Aspyr related

### ISSUE THREAD

**Issue by Nostritius** [xoreos/xoreos-tools#28]
I read a bit about android development and found out that obb files do not look like they are not specifically related to Aspyr but rather a common android container for large amounts of files ([See also](https://developer.android.com/google/play/expansion-files)), since android play requires apk to not exceed a size of 100Mb. Maybe it would be wirth to change some notes to make clear it is something android specific to avoid confusion, like it did for me.

**Comment by DrMcCoy** [comment]
From what I gathered, any generic storage object an Android game can access is named ".obb". What's *in* these obb files is completely arbitrary and up to the game in question. I.e. it could have been called ".dat" or anything else generic.

The actual format of the file data inside the ".obb" file for KotOR is Aspyr-specific. Or at least something Aspyr bought. Other games have different stuff inside the ".obb". I've seen people say an ".obb" in a game is a RAR, or other things.

Jade Empire, for example, has ".obb" files which are actually ZIPs.

**Comment by DrMcCoy** [comment]
Just downloaded the official Android SDK command line tools (https://developer.android.com/studio/), where the jobb tool is in, and yes, it can't read the KotOR OBB files, and the OBB files it creates look completely different structurally.

**Comment by Nostritius** [comment]
Ah, thanks for the clarification
