### ISSUE TITLE
xoreos 0.0.5 tools won't run on Windows 7

### ISSUE THREAD

**Issue by JCarter426** [xoreos/xoreos-tools#32]
I did some poking around and according to what I've found, this is probably a Windows problem rather than a xoreos problem and might not be worth fixing. But I figured I ought to make it known that there is an issue in case it becomes a problem for someone else.

Whenever I try to use at tool from the 0.0.5 release, I get the following error message:
`The procedure entry point _create_locale could not be located in the dynamic link library msvcrt.dll.`
I found some old error reports for other software that suggest this issue is specific to Visual C++ on Windows 7. According to users from ages past, it shouldn't happen on Windows 8 or 10. And of course I know people who can run the 0.0.5 release tools on Windows 10 successfully, and they work for me on Linux. The 0.0.4 release tools also do run on Windows 7 for me, so the issue is probably limited to the most recent update. I can run the tools just fine on Linux or by downgrading for Windows 7, so no pressure or anything to fix them on my account.

**Comment by JCarter426** [comment]
Yup, that sounds like it all right.

**Comment by DrMcCoy** [comment]
Seems to be some weird interplay between ICU and mingw. I'll see if I can resolve that somehow when I find some time.

Thanks for notifying us! :)

**Comment by DrMcCoy** [comment]
Oh, I still need to look at that as well. I consider that a blocker for a new release (which we've been talking about).

I do have a mingw-w64 8.3.0 set up now as well. If I throw a new test build of the xoreos-tools your way, @JCarter426, on the weekend, could you test it for me?

**Comment by JCarter426** [comment]
Sure.

**Comment by DrMcCoy** [comment]
- [xoreos-tools-0.0.5-win32.zip](https://drmccoy.de/zeugs/xoreos-tools-0.0.5-win32.zip)
- [xoreos-tools-0.0.5-win64.zip](https://drmccoy.de/zeugs/xoreos-tools-0.0.5-win64.zip)

Based on 93122d55615cd32697dada71d2e903b58eec67db, built with mingw-w64 8.3.0 and ICU 63.1.

Please tell me if it's still broken with these.

**Comment by JCarter426** [comment]
I can confirm that tools now work on Windows 7 64-bit. I tested tlk2xml, xml2tlk, all with no errors. I also ran the help option on a few others and that displayed correctly too, so I assume they're all working. Good job!

**Comment by DrMcCoy** [comment]
Yay. Thanks for alerting and checking! :)
