### ISSUE TITLE
CMAKE Build - xml issue / error

### ISSUE THREAD

**Issue by Glog78** [xoreos/xoreos-tools#4]
The cmake build can't link the tools while the combination of autogen.sh , configure , make can.
Here is the log file

[buildlog.txt](https://github.com/xoreos/xoreos-tools/files/46673/buildlog.txt)

System: Archlinux current

**Comment by DrMcCoy** [comment]
Oh, yes, that's my bad. When I transfered the XML test over from the xoreos CMake file (without properly testing it, it seems), I forgot to change XOREOS_LIBRARIES to XOREOSTOOLS_LIBRARIES in line 146.
