### ISSUE TITLE
ERF: MOD files have incorrect prefix

### ISSUE THREAD

**Issue by lachjames** [xoreos/xoreos-tools#64]
Hi :)

The first eight bytes of a mod file saved with ERF v1.0 should read "MOD V1.0", but they read "ERF V1.0" instead. This apparently causes TSL to be unable to open the archive, where manually hex-editing the first eight bytes to the correct value allows the archive to be opened.

**Comment by DrMcCoy** [comment]
ERF files come in several flavours: ERF (used by the NWN toolset as general resources archives), MOD (modules), HAK (used by NWN as additional resource archives loaded by a modules) and SAV (save files).

With our `erf` archive packer, you can select those with the command line flag `--erf` (default), `--mod`, `--hak` or `--sav`, respectively.

**Comment by DrMcCoy** [comment]
Ah, well, and this is currently broken. Damn.

**Comment by lachjames** [comment]
Yeah, can confirm that --mod didn't work. Thanks @DrMcCoy :)

**Comment by DrMcCoy** [comment]
Should be fixed with d5eb9a4297a4a7b5fd0841dcae4a62fa7a9c7310, thanks for reporting!
