### ISSUE TITLE
ERF: Recursion leads to infinite loop

### ISSUE THREAD

**Issue by lachjames** [xoreos/xoreos-tools#65]
Hi :)

When packing an ERF file into itself (e.g. with "_erf --mod output.mod files ... output.mod_"), it seems an infinite loop is triggered which is only exited when the 4GB file size limit is reached. This issue might exist in the other archive tools as well but I have observed it for ERF at least.

**Comment by DrMcCoy** [comment]
Fixed, thanks for reporting!
