### ISSUE TITLE
error while compiling

### ISSUE THREAD

**Issue by bleau2000** [xoreos/xoreos-tools#75]
i get this error while compiling can somebody help please

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'external_mspack.lib'	C:\Users\sebas\Downloads\xoreos-tools-master\xoreos-tools-master\out\build\x64-Debug\xoreos-tools-master	C:\Users\sebas\Downloads\xoreos-tools-master\xoreos-tools-master\out\build\x64-Debug\LINK	1

**Comment by DrMcCoy** [comment]
Oh, you're right. A recent changed pulled in mspack and we've forgotten to update the CMake build script.

Thanks for finding this! Should be fixed with d8571ed. Please update your checkout (and reapply the unobb patch) and retry.

**Comment by bleau2000** [comment]
it give me this error in log 

Determining if the include file pthread.h exists failed with the following output:
Change Dir: C:/Users/sebas/OneDrive/Desktop/xoreos-tools/out/build/x64-Debug/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_689b7 && [1/2] Building C object CMakeFiles\cmTC_689b7.dir\CheckIncludeFile.c.obj

FAILED: CMakeFiles/cmTC_689b7.dir/CheckIncludeFile.c.obj 

C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1430~1.307\bin\Hostx64\x64\cl.exe  /nologo   /DWIN32 /D_WINDOWS /W3  /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\cmTC_689b7.dir\CheckIncludeFile.c.obj /FdCMakeFiles\cmTC_689b7.dir\ /FS -c C:\Users\sebas\OneDrive\Desktop\xoreos-tools\out\build\x64-Debug\CMakeFiles\CMakeTmp\CheckIncludeFile.c

C:\Users\sebas\OneDrive\Desktop\xoreos-tools\out\build\x64-Debug\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
ninja: build stopped: subcommand failed.




Performing C++ SOURCE FILE Test ICONV_SECOND_ARGUMENT_IS_CONST failed with the following output:
Change Dir: C:/Users/sebas/OneDrive/Desktop/xoreos-tools/out/build/x64-Debug/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_00236 && [1/2] Building CXX object CMakeFiles\cmTC_00236.dir\src.cxx.obj

FAILED: CMakeFiles/cmTC_00236.dir/src.cxx.obj 

C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1430~1.307\bin\Hostx64\x64\cl.exe  /nologo /TP -DICONV_SECOND_ARGUMENT_IS_CONST -IC:\dev\cpp\vcpkg\packages\libiconv_x86-windows /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MP /bigobj  /wd4250 /wd4100 /wd4127 /wd4189 /wd4245 /wd4435 /wd4510 /wd4512 /wd4610 /wd4706 /wd4710 /wd4714 /wd4305 /wd4244 /wd4267 /wd4996   /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\cmTC_00236.dir\src.cxx.obj /FdCMakeFiles\cmTC_00236.dir\ /FS -c C:\Users\sebas\OneDrive\Desktop\xoreos-tools\out\build\x64-Debug\CMakeFiles\CMakeTmp\src.cxx

C:\Users\sebas\OneDrive\Desktop\xoreos-tools\out\build\x64-Debug\CMakeFiles\CMakeTmp\src.cxx(2): fatal error C1083: Cannot open include file: 'iconv.h': No such file or directory
ninja: build stopped: subcommand failed.



Source file was:

  #include <iconv.h>
    int main(){
    iconv_t conv = 0;
    const char* in = 0;
    size_t ilen = 0;
    char* out = 0;
    size_t olen = 0;
    iconv(conv, &in, &ilen, &out, &olen);
    return 0;
  }

**Comment by DrMcCoy** [comment]
That sounds like you're missing the [library dependencies](https://wiki.xoreos.org/index.php?title=Compiling_xoreos-tools#Libraries). iconv and pthread, in this case.

You also need zlib, liblzma, libxml2 and Boost.

**Comment by bleau2000** [comment]
iconv est intaller via pcpkg dans le dossier package

**Comment by DrMcCoy** [comment]
Frankly, I'm not sure how MSVC really works, I'm using a cross-compiling mingw on Linux and I know that msys2 works (which also installs a mingw).

We have [an AppVeyor config file](https://github.com/xoreos/xoreos-tools/blob/master/.appveyor.yml) you could look at to see how MSVC might be set up. However, our AppVeyor setup is also somewhat broken, and I don't really get why, since Windows isn't really my thing.

**Comment by bleau2000** [comment]
i have tried msys2 but i cant get it to work after i installl cmake  when irun the its says cmake make in the build directory  its says cmake:invaslid command

**Comment by bleau2000** [comment]
i have tried msys2 but when i launch cmake make command its says :  The system is: Windows - 10.0.19043 - AMD64
