### ISSUE TITLE
another error while compiling

### ISSUE THREAD

**Issue by bleau2000** [xoreos/xoreos-tools#76]
it give me this error in log

Determining if the include file pthread.h exists failed with the following output:
Change Dir: C:/Users/sebas/OneDrive/Desktop/xoreos-tools/out/build/x64-Debug/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_689b7 && [1/2] Building C object CMakeFiles\cmTC_689b7.dir\CheckIncludeFile.c.obj

FAILED: CMakeFiles/cmTC_689b7.dir/CheckIncludeFile.c.obj

C:\PROGRA1\MICROS3\2022\COMMUN1\VC\Tools\MSVC\14301.307\bin\Hostx64\x64\cl.exe /nologo /DWIN32 /D_WINDOWS /W3 /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\cmTC_689b7.dir\CheckIncludeFile.c.obj /FdCMakeFiles\cmTC_689b7.dir\ /FS -c C:\Users\sebas\OneDrive\Desktop\xoreos-tools\out\build\x64-Debug\CMakeFiles\CMakeTmp\CheckIncludeFile.c

C:\Users\sebas\OneDrive\Desktop\xoreos-tools\out\build\x64-Debug\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
ninja: build stopped: subcommand failed.

Performing C++ SOURCE FILE Test ICONV_SECOND_ARGUMENT_IS_CONST failed with the following output:
Change Dir: C:/Users/sebas/OneDrive/Desktop/xoreos-tools/out/build/x64-Debug/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_00236 && [1/2] Building CXX object CMakeFiles\cmTC_00236.dir\src.cxx.obj

FAILED: CMakeFiles/cmTC_00236.dir/src.cxx.obj

C:\PROGRA1\MICROS3\2022\COMMUN1\VC\Tools\MSVC\14301.307\bin\Hostx64\x64\cl.exe /nologo /TP -DICONV_SECOND_ARGUMENT_IS_CONST -IC:\dev\cpp\vcpkg\packages\libiconv_x86-windows /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MP /bigobj /wd4250 /wd4100 /wd4127 /wd4189 /wd4245 /wd4435 /wd4510 /wd4512 /wd4610 /wd4706 /wd4710 /wd4714 /wd4305 /wd4244 /wd4267 /wd4996 /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\cmTC_00236.dir\src.cxx.obj /FdCMakeFiles\cmTC_00236.dir\ /FS -c C:\Users\sebas\OneDrive\Desktop\xoreos-tools\out\build\x64-Debug\CMakeFiles\CMakeTmp\src.cxx

C:\Users\sebas\OneDrive\Desktop\xoreos-tools\out\build\x64-Debug\CMakeFiles\CMakeTmp\src.cxx(2): fatal error C1083: Cannot open include file: 'iconv.h': No such file or directory
ninja: build stopped: subcommand failed.

Source file was:

#include <iconv.h>
int main(){
iconv_t conv = 0;
const char* in = 0;
size_t ilen = 0;
char* out = 0;
size_t olen = 0;
iconv(conv, &in, &ilen, &out, &olen);
return 0;
}

**Comment by DrMcCoy** [comment]
That sounds like you're missing the [library dependencies](https://wiki.xoreos.org/index.php?title=Compiling_xoreos-tools#Libraries). iconv and pthread, in this case.

You also need zlib, liblzma, libxml2 and Boost.
